/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HomeBlog = {
  _type: "homeBlog";
  sectionTitle?: string;
  sectionSubTitle?: string;
  allArticleButton?: CallToAction;
};

export type BlogImage = {
  _type: "blogImage";
  layoutType?: "three" | "two" | "full";
  fullImage?: CustomImage;
  twoColImages?: Array<{
    _key: string;
  } & CustomImage>;
  threeColImages?: Array<{
    _key: string;
  } & CustomImage>;
};

export type FleetManagement = {
  _type: "fleetManagement";
  title?: string;
  companyAndFleetDetails?: {
    heading?: string;
    companyNameLabel?: string;
    companyNamePlaceholder?: string;
    managerFirstNameLabel?: string;
    managerFirstNamePlaceholder?: string;
    managerLastNameLabel?: string;
    managerLastNamePlaceholder?: string;
    emailLabel?: string;
    emailPlaceholder?: string;
    countryLabel?: string;
    contactNumberLabel?: string;
    contactNumberPlaceholder?: string;
  };
  fleetDetails?: {
    heading?: string;
    numberOfVehicleLabel?: string;
    numberOfVehiclePlaceholder?: string;
    prferedGarageLabel?: string;
    prferedGaragePlaceholder?: string;
  };
  submitText?: string;
};

export type ContactUsForm = {
  _type: "contactUsForm";
  title?: string;
  heading?: string;
  firstNameLabel?: string;
  firstNamePlaceholder?: string;
  lastNameLabel?: string;
  lastNamePlaceholder?: string;
  emailLabel?: string;
  emailPlaceholder?: string;
  countryLabel?: string;
  contactNumberLabel?: string;
  contactNumberPlaceholder?: string;
  subjectLabel?: string;
  subjectPlaceholder?: string;
  queryBoxLabel?: string;
  queryBoxPlaceholder?: string;
  submitBtnText?: string;
};

export type ExtendedWarrantyForm = {
  _type: "extendedWarrantyForm";
  personalDetails?: {
    heading?: string;
    firstname?: {
      label?: string;
      placeholder?: string;
    };
    lastname?: {
      label?: string;
      placeholder?: string;
    };
    email?: {
      label?: string;
      placeholder?: string;
    };
    contact?: {
      country?: {
        label?: string;
        placeholder?: string;
      };
      countryCode?: Array<number>;
      phone?: {
        label?: string;
        placeholder?: string;
      };
    };
  };
  vehicleDetails?: {
    heading?: string;
    vin?: {
      label?: string;
      placeholder?: string;
    };
    plateNumber?: {
      label?: string;
      placeholder?: string;
    };
    brand?: {
      labelPlaceholder?: {
        label?: string;
        placeholder?: string;
      };
    };
    model?: {
      labelPlaceholder?: {
        label?: string;
        placeholder?: string;
      };
    };
    year?: {
      labelPlaceholder?: {
        label?: string;
        placeholder?: string;
      };
      years?: Array<number>;
    };
    odometer?: {
      labelPlaceholder?: {
        label?: string;
        placeholder?: string;
      };
    };
  };
  submitButton?: CallToAction;
};

export type ServiceCard = {
  _type: "serviceCard";
  serviceCode?: string;
  title?: string;
  warranty?: string;
  recommendation?: boolean;
  interval?: string;
  duration?: string;
  features?: Array<string>;
  price?: {
    original?: number;
    discounted?: number;
    discountPercentage?: number;
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctaLabel?: string;
};

export type Location = {
  _type: "location";
  heading?: string;
  subHeading?: string;
  directionsButtonLabel?: string;
  mobileButton?: string;
  showFilters?: boolean;
  locations?: Array<{
    mapId?: string;
    title?: string;
    serviceName?: string;
    poptitle?: string;
    phoneNo?: string;
    address?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    timingLabel1?: string;
    workingHours?: string;
    fridayTiming?: {
      fridayTimingLabel?: string;
      morning?: string;
      evening?: string;
    };
    timingLabel3?: string;
    saturdayTime?: string;
    mapUrl?: string;
    coordinates?: {
      x?: number;
      y?: number;
    };
    relatedServices?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "service";
    }>;
    _key: string;
  }>;
};

export type ServiceCart = {
  _type: "serviceCart";
  heading?: string;
  subHeading?: string;
  serviceTitle?: string;
  browseServiceLabel?: string;
  chengeLabel?: string;
  verifySection?: Array<{
    verify?: string;
    countryLabel?: string;
    otpLabel?: string;
    verifyBtnLabel?: string;
    sendOtpButtonLabel?: string;
    sendOtpLabel?: string;
    editBtnLabel?: string;
    _type: "verify";
    _key: string;
  }>;
  appointmentSection?: Array<{
    appointment?: string;
    selectWorkShopLabel?: string;
    workshopPlaceholder?: string;
    availableTimeSlotLabel?: string;
    timeSlotLabel?: string;
    continueBtnLabel?: string;
    editBtnLabel?: string;
    _type: "appointment";
    _key: string;
  }>;
  personalDetailsSection?: Array<{
    appointment?: string;
    fullNameLabel?: string;
    emailLabel?: string;
    verifyYourNameLabel?: string;
    declaration?: string;
    continueBtnLabel?: string;
    editBtnLabel?: string;
    _type: "personalDetails";
    _key: string;
  }>;
  cartSection?: Array<{
    heading?: string;
    scheduleLabel?: string;
    emptyCartHeading?: string;
    emptyCartSubHeading?: string;
    emptyCartImage?: CustomImage;
    submittedBntLable?: string;
    _type: "cart";
    _key: string;
  }>;
};

export type ServiceBookedTesla = {
  _type: "serviceBookedTesla";
  heading?: string;
};

export type ServiceBooked = {
  _type: "serviceBooked";
  titles?: {
    title?: string;
    subTitle?: string;
  };
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  nextSteps?: {
    steps?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    stepsBackgroundImage?: CustomImage;
  };
  BookingSummary?: {
    title?: string;
    vehicleWorkshop?: string;
    custroInfo?: string;
    branchLabel?: string;
    nameLabel?: string;
    emialLabel?: string;
    contactLabel?: string;
    brandLabel?: string;
    modelLabel?: string;
    plateNoLabel?: string;
    vehicleDetails?: string;
  };
};

export type LinkItem = {
  _type: "linkItem";
  linkText?: string;
  link?: Link;
};

export type ServiceListing = {
  _type: "serviceListing";
  heading?: string;
};

export type FaqSection = {
  _type: "faqSection";
  heading?: string;
};

export type Testimonial = {
  _type: "testimonial";
  heading?: string;
  subHeading?: string;
};

export type LogoList = {
  _type: "logoList";
  heading?: string;
  logoList?: Array<{
    logoImage?: CustomImage;
    _type: "logo";
    _key: string;
  }>;
};

export type CarServicesList = {
  _type: "carServicesList";
  heading?: string;
  scheduleNow?: string;
  muchMore?: string;
  browseAll?: string;
  serviceCard?: Array<{
    title?: string;
    scheduleNow?: string;
    thumbnailImage?: CustomImage;
    selectServiceLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "service";
    };
    _type: "cards";
    _key: string;
  }>;
};

export type LocaleText = {
  _type: "localeText";
  en?: string;
  ar?: string;
};

export type TermsAndConditionSection = {
  _type: "termsAndConditionSection";
  title?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HomeWorkFlow = {
  _type: "homeWorkFlow";
  image?: CustomImage;
  heading?: string;
  workFlow?: Array<{
    workName?: string;
    workDesc?: string;
    _type: "work";
    _key: string;
  }>;
};

export type HomeHeroSlider = {
  _type: "homeHeroSlider";
  vimeoId?: string;
  buttonText?: string;
  buttonLink?: string;
  heading?: string;
  subHeading?: string;
  slides?: Array<{
    desktopImage?: CustomImage;
    desktopImageLight?: CustomImage;
    mobileImage?: CustomImage;
    buttonText?: string;
    buttonUrl?: string;
    heading?: string;
    subHeading?: string;
    _type: "slide";
    _key: string;
  }>;
  brandName?: string;
  brandPlaceholder?: string;
  brandModelName?: string;
  brandModelPlaceholder?: string;
  SearchButtonText?: string;
};

export type RichTextTitle = {
  _type: "richTextTitle";
  aboutsection?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HomeCta = {
  _type: "homeCta";
  heading?: string;
  subHeading?: string;
  leftImage?: CustomImage;
  mobileLeftImage?: CustomImage;
  ButtonUrl?: CallToAction;
};

export type ImageRichText = {
  _type: "imageRichText";
  leftImage?: CustomImage;
  aboutAutocare?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type RichText = {
  _type: "richText";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  htmlId?: string;
};

export type ScrollContent = {
  _type: "scrollContent";
  title?: Array<string>;
};

export type HomeFleet = {
  _type: "homeFleet";
  RightImage?: CustomImage;
  imageAlign?: "left" | "right";
  aboutFleet?: {
    heading?: string;
    subHeading?: string;
    decription?: string;
    topLogo?: CustomImage;
    button?: string;
    buttonLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
  };
};

export type HomeIntro = {
  _type: "homeIntro";
  heading?: string;
  subheading?: string;
  introText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  leftBottomImage?: CustomImage;
  rihgtTopImage?: CustomImage;
};

export type HomeTesla = {
  _type: "homeTesla";
  brand?: "tesla" | "lucid";
  marginBottom?: boolean;
  imageAlign?: "left" | "right";
  leftImage?: CustomImage;
  bottmRightImage?: CustomImage;
  aboutTesla?: {
    heading?: string;
    subHeading?: string;
    decription?: string;
    topLogo?: CustomImage;
    BottomLogo?: CustomImage;
    button?: CallToAction;
  };
  teslaForm?: TeslaForm;
};

export type TeslaForm = {
  _type: "teslaForm";
  whiteHeading?: string;
  redHeading?: string;
  teslaImage?: CustomImage;
  teslaLogo?: CustomImage;
  stepOne?: {
    countryLabel?: string;
    phoneLabel?: string;
    phonePlaceholder?: string;
    modelLabel?: string;
    modelPlaceholder?: string;
    yearLabel?: string;
    yearPlaceholder?: string;
    years?: Array<string>;
    plateNumberLabel?: string;
    plateNumberPlaceholder?: string;
    proceed?: string;
  };
  stepTwo?: {
    workshopLabel?: string;
    workshopPlaceholder?: string;
    selectAndProceed?: string;
  };
  stepThree?: {
    fullNameLabel?: string;
    fullNamePlaceholder?: string;
    emailLabel?: string;
    emailPlaceholder?: string;
    declaration?: string;
    scheduleAppointment?: string;
  };
};

export type Link = {
  _type: "link";
  linkType?: "href" | "page" | "post";
  href?: string;
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  openInNewTab?: boolean;
};

export type InfoSection = {
  _type: "infoSection";
  heading?: string;
  subheading?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "href" | "page" | "post";
    href?: string;
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type LinkList = {
  _type: "linkList";
  title?: string;
  links?: Array<{
    _key: string;
  } & LinkItem>;
};

export type Testimonials = {
  _id: string;
  _type: "testimonials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  review?: LocaleBlockContent;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  name?: LocaleString;
  profession?: string;
  stars?: "1" | "2" | "3" | "4" | "5";
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: LocaleString;
  answer?: LocaleBlockContent;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  en?: BlockContent;
  ar?: BlockContent;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
  fragmentItem?: {
    pitstopContact?: string;
    pitstopEmail?: string;
    addressLine1?: LocaleString;
    addressLine2?: LocaleString;
    openTime?: string;
    closeTime?: string;
    OpenDay?: LocaleString;
    endDay?: LocaleString;
    followUs?: LocaleString;
    facebookTitle?: LocaleString;
    facebookLink?: string;
    instagramTitle?: LocaleString;
    instagramLink?: string;
    twitterTitle?: LocaleString;
    twitterLink?: string;
    youtubeTitle?: LocaleString;
    youtubeLink?: string;
  };
  addThisService?: LocaleString;
  addVehicleToContinue?: LocaleString;
  serviceAdded?: LocaleString;
  recommended?: LocaleString;
  serviceAlert?: LocaleString;
  bookService?: LocaleString;
  bookServiceDes?: LocaleString;
  addVehicle?: LocaleString;
  testimonialHeading?: LocaleString;
  testimonialSubHeading?: LocaleString;
  faqTitle?: LocaleString;
  serviceBookForm?: {
    carImage?: CustomImage;
    stepOne?: {
      whiteHeading?: LocaleString;
      redHeading?: LocaleString;
      brandLabel?: LocaleString;
      brandPlaceholder?: LocaleString;
      modelLabel?: LocaleString;
      modelPlaceholder?: LocaleString;
      yearLabel?: LocaleString;
      yearPlaceholder?: LocaleString;
      numberPlateLabel?: LocaleString;
      numberPlatePlaceholder?: LocaleString;
      proceedBtn?: LocaleString;
    };
    stepTwo?: {
      whiteHeading?: LocaleString;
      redHeading?: LocaleString;
      nameLabel?: LocaleString;
      namePlaceholder?: LocaleString;
      countryLabel?: LocaleString;
      phoneLabel?: LocaleString;
      phonePlaceholder?: LocaleString;
      emailLabel?: LocaleString;
      emailPlaceholder?: LocaleString;
      proceedBtn?: LocaleString;
    };
  };
  brands?: Array<{
    carImage?: CustomImage;
    brandTitle?: string;
    brandValue?: string;
    _type: "brand";
    _key: string;
  }>;
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  ar?: string;
};

export type Tags = Array<{
  _key: string;
} & Tag>;

export type Tag = {
  _type: "tag";
  value?: string;
  label?: string;
};

export type MetaTag = {
  _type: "metaTag";
  metaAttributes?: Array<{
    _key: string;
  } & MetaAttribute>;
};

export type MetaAttribute = {
  _type: "metaAttribute";
  attributeKey?: string;
  attributeType?: "string" | "image";
  attributeValueImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  attributeValueString?: string;
};

export type Twitter = {
  _type: "twitter";
  cardType?: string;
  creator?: string;
  site?: string;
  handle?: string;
};

export type OpenGraph = {
  _type: "openGraph";
  url?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  siteName?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type InternationalizedArrayText = Array<{
  _key: string;
} & InternationalizedArrayTextValue>;

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: Array<{
    _key: string;
  } & InternationalizedArrayReferenceValue>;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "fragment";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "offer";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "service";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  };
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  IsHomePage?: boolean;
  categoryTags?: Tags;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  blogDate?: string;
  thumbnailImage?: CustomImage;
  blogImage?: CustomImage;
  pageBuilder?: Array<{
    _key: string;
  } & RichText | {
    _key: string;
  } & BlogImage>;
  language?: "en" | "ar";
};

export type Offer = {
  _id: string;
  _type: "offer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  thumbnail?: CustomImage;
  buttonText?: string;
  detailImage?: CustomImage;
  richText?: Array<{
    offerRichText?: BlockContent;
    _type: "richText";
    _key: string;
  }>;
  language?: "en" | "ar";
};

export type Fragment = {
  _id: string;
  _type: "fragment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "Header" | "Footer";
  header?: Header;
  footer?: Footer;
  language?: "en" | "ar";
};

export type Footer = {
  _type: "footer";
  centerFarrari?: CustomImage;
  servicesList?: LinkList;
  linkList?: LinkList;
  agmcLogo?: CustomImage;
  copyrightText?: string;
  footerLogo2?: CustomImage;
  privacyPolicyLink?: LinkList;
};

export type Header = {
  _type: "header";
  callUs?: string;
  contact?: string;
  lang?: LocaleString;
  headerLogo?: CustomImage;
  cornerLogo?: string;
  headerLink?: LinkList;
  privacyPolicyLink?: LinkList;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<{
    _key: string;
  } & CallToAction | {
    _key: string;
  } & InfoSection | {
    _key: string;
  } & HomeTesla | {
    _key: string;
  } & HomeIntro | {
    _key: string;
  } & HomeFleet | {
    _key: string;
  } & ScrollContent | {
    _key: string;
  } & ImageRichText | {
    _key: string;
  } & RichTextTitle | {
    _key: string;
  } & HomeCta | {
    _key: string;
  } & HomeWorkFlow | {
    _key: string;
  } & HomeHeroSlider | {
    _key: string;
  } & TermsAndConditionSection | {
    _key: string;
  } & CarServicesList | {
    _key: string;
  } & LogoList | {
    _key: string;
  } & Testimonial | {
    _key: string;
  } & FaqSection | {
    _key: string;
  } & ServiceListing | {
    _key: string;
  } & ServiceBooked | {
    _key: string;
  } & ServiceBookedTesla | {
    _key: string;
  } & ServiceCart | {
    _key: string;
  } & Location | {
    _key: string;
  } & ExtendedWarrantyForm | {
    _key: string;
  } & ContactUsForm | {
    _key: string;
  } & FleetManagement | {
    _key: string;
  } & TeslaForm | {
    _key: string;
  } & HomeBlog>;
  seo?: SeoMetaFields;
  language?: "en" | "ar";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  serviceIcon?: CustomImage;
  thumbnail?: CustomImage;
  shceduleNow?: string;
  pageBuilder?: Array<{
    _key: string;
  } & ServiceCard>;
  noVehicleImage?: CustomImage;
  noVehicleHeading?: string;
  noVehicleText?: string;
  addVehicleLabel?: string;
  emptyCartCarImage?: CustomImage;
  heading?: string;
  subHeading?: string;
  browseServiceCtaLabel?: string;
  changeCtaLabel?: string;
  cartLabel?: string;
  estimatedTotalLabel?: string;
  taxLabel?: string;
  submitCtaLabel?: string;
  seo?: SeoMetaFields;
  language?: "en" | "ar";
};

export type SeoMetaFields = {
  _type: "seoMetaFields";
  nofollowAttributes?: boolean;
  metaTitle?: string;
  metaDescription?: string;
  metaImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoKeywords?: Array<string>;
  openGraph?: OpenGraph;
  additionalMetaTags?: Array<{
    _key: string;
  } & MetaTag>;
  twitter?: Twitter;
};

export type CallToAction = {
  _type: "callToAction";
  buttonText?: string;
  link?: Link;
};

export type CustomImage = {
  _type: "customImage";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  altText?: string;
  isImageFullWidth?: boolean;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: BlockContent;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  picture?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = HomeBlog | BlogImage | FleetManagement | ContactUsForm | ExtendedWarrantyForm | ServiceCard | Location | ServiceCart | ServiceBookedTesla | ServiceBooked | LinkItem | ServiceListing | FaqSection | Testimonial | LogoList | CarServicesList | LocaleText | TermsAndConditionSection | HomeWorkFlow | HomeHeroSlider | RichTextTitle | HomeCta | ImageRichText | RichText | ScrollContent | HomeFleet | HomeIntro | HomeTesla | TeslaForm | Link | InfoSection | BlockContent | LinkList | Testimonials | Faq | LocaleBlockContent | Settings | LocaleString | Tags | Tag | MetaTag | MetaAttribute | Twitter | OpenGraph | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | InternationalizedArrayTextValue | InternationalizedArrayStringValue | InternationalizedArrayText | InternationalizedArrayString | TranslationMetadata | InternationalizedArrayReferenceValue | Blog | Offer | Fragment | Footer | Header | Page | Service | SeoMetaFields | CallToAction | CustomImage | Post | Person | InternationalizedArrayReference | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
  fragmentItem?: {
    pitstopContact?: string;
    pitstopEmail?: string;
    addressLine1?: LocaleString;
    addressLine2?: LocaleString;
    openTime?: string;
    closeTime?: string;
    OpenDay?: LocaleString;
    endDay?: LocaleString;
    followUs?: LocaleString;
    facebookTitle?: LocaleString;
    facebookLink?: string;
    instagramTitle?: LocaleString;
    instagramLink?: string;
    twitterTitle?: LocaleString;
    twitterLink?: string;
    youtubeTitle?: LocaleString;
    youtubeLink?: string;
  };
  addThisService?: LocaleString;
  addVehicleToContinue?: LocaleString;
  serviceAdded?: LocaleString;
  recommended?: LocaleString;
  serviceAlert?: LocaleString;
  bookService?: LocaleString;
  bookServiceDes?: LocaleString;
  addVehicle?: LocaleString;
  testimonialHeading?: LocaleString;
  testimonialSubHeading?: LocaleString;
  faqTitle?: LocaleString;
  serviceBookForm?: {
    carImage?: CustomImage;
    stepOne?: {
      whiteHeading?: LocaleString;
      redHeading?: LocaleString;
      brandLabel?: LocaleString;
      brandPlaceholder?: LocaleString;
      modelLabel?: LocaleString;
      modelPlaceholder?: LocaleString;
      yearLabel?: LocaleString;
      yearPlaceholder?: LocaleString;
      numberPlateLabel?: LocaleString;
      numberPlatePlaceholder?: LocaleString;
      proceedBtn?: LocaleString;
    };
    stepTwo?: {
      whiteHeading?: LocaleString;
      redHeading?: LocaleString;
      nameLabel?: LocaleString;
      namePlaceholder?: LocaleString;
      countryLabel?: LocaleString;
      phoneLabel?: LocaleString;
      phonePlaceholder?: LocaleString;
      emailLabel?: LocaleString;
      emailPlaceholder?: LocaleString;
      proceedBtn?: LocaleString;
    };
  };
  brands?: Array<{
    carImage?: CustomImage;
    brandTitle?: string;
    brandValue?: string;
    _type: "brand";
    _key: string;
  }>;
} | null;
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {          link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      },      },      _type == "location" => {      ...,      locations[]{         ...,        "relatedServices": relatedServices[]->{            _id,            title,            slug,            _type          }      }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string;
  _type: "page";
  name: null;
  slug: Slug | null;
  heading: null;
  subheading: null;
  pageBuilder: Array<{
    _key: string;
    _type: "callToAction";
    buttonText?: string;
    link: {
      _type: "link";
      linkType?: "href" | "page" | "post";
      href?: string;
      page: string | null;
      post: string | null;
      openInNewTab?: boolean;
    } | null;
  } | {
    _key: string;
    _type: "carServicesList";
    heading?: string;
    scheduleNow?: string;
    muchMore?: string;
    browseAll?: string;
    serviceCard?: Array<{
      title?: string;
      scheduleNow?: string;
      thumbnailImage?: CustomImage;
      selectServiceLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "service";
      };
      _type: "cards";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "contactUsForm";
    title?: string;
    heading?: string;
    firstNameLabel?: string;
    firstNamePlaceholder?: string;
    lastNameLabel?: string;
    lastNamePlaceholder?: string;
    emailLabel?: string;
    emailPlaceholder?: string;
    countryLabel?: string;
    contactNumberLabel?: string;
    contactNumberPlaceholder?: string;
    subjectLabel?: string;
    subjectPlaceholder?: string;
    queryBoxLabel?: string;
    queryBoxPlaceholder?: string;
    submitBtnText?: string;
  } | {
    _key: string;
    _type: "extendedWarrantyForm";
    personalDetails?: {
      heading?: string;
      firstname?: {
        label?: string;
        placeholder?: string;
      };
      lastname?: {
        label?: string;
        placeholder?: string;
      };
      email?: {
        label?: string;
        placeholder?: string;
      };
      contact?: {
        country?: {
          label?: string;
          placeholder?: string;
        };
        countryCode?: Array<number>;
        phone?: {
          label?: string;
          placeholder?: string;
        };
      };
    };
    vehicleDetails?: {
      heading?: string;
      vin?: {
        label?: string;
        placeholder?: string;
      };
      plateNumber?: {
        label?: string;
        placeholder?: string;
      };
      brand?: {
        labelPlaceholder?: {
          label?: string;
          placeholder?: string;
        };
      };
      model?: {
        labelPlaceholder?: {
          label?: string;
          placeholder?: string;
        };
      };
      year?: {
        labelPlaceholder?: {
          label?: string;
          placeholder?: string;
        };
        years?: Array<number>;
      };
      odometer?: {
        labelPlaceholder?: {
          label?: string;
          placeholder?: string;
        };
      };
    };
    submitButton?: CallToAction;
  } | {
    _key: string;
    _type: "faqSection";
    heading?: string;
  } | {
    _key: string;
    _type: "fleetManagement";
    title?: string;
    companyAndFleetDetails?: {
      heading?: string;
      companyNameLabel?: string;
      companyNamePlaceholder?: string;
      managerFirstNameLabel?: string;
      managerFirstNamePlaceholder?: string;
      managerLastNameLabel?: string;
      managerLastNamePlaceholder?: string;
      emailLabel?: string;
      emailPlaceholder?: string;
      countryLabel?: string;
      contactNumberLabel?: string;
      contactNumberPlaceholder?: string;
    };
    fleetDetails?: {
      heading?: string;
      numberOfVehicleLabel?: string;
      numberOfVehiclePlaceholder?: string;
      prferedGarageLabel?: string;
      prferedGaragePlaceholder?: string;
    };
    submitText?: string;
  } | {
    _key: string;
    _type: "homeBlog";
    sectionTitle?: string;
    sectionSubTitle?: string;
    allArticleButton?: CallToAction;
  } | {
    _key: string;
    _type: "homeCta";
    heading?: string;
    subHeading?: string;
    leftImage?: CustomImage;
    mobileLeftImage?: CustomImage;
    ButtonUrl?: CallToAction;
  } | {
    _key: string;
    _type: "homeFleet";
    RightImage?: CustomImage;
    imageAlign?: "left" | "right";
    aboutFleet?: {
      heading?: string;
      subHeading?: string;
      decription?: string;
      topLogo?: CustomImage;
      button?: string;
      buttonLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
  } | {
    _key: string;
    _type: "homeHeroSlider";
    vimeoId?: string;
    buttonText?: string;
    buttonLink?: string;
    heading?: string;
    subHeading?: string;
    slides?: Array<{
      desktopImage?: CustomImage;
      desktopImageLight?: CustomImage;
      mobileImage?: CustomImage;
      buttonText?: string;
      buttonUrl?: string;
      heading?: string;
      subHeading?: string;
      _type: "slide";
      _key: string;
    }>;
    brandName?: string;
    brandPlaceholder?: string;
    brandModelName?: string;
    brandModelPlaceholder?: string;
    SearchButtonText?: string;
  } | {
    _key: string;
    _type: "homeIntro";
    heading?: string;
    subheading?: string;
    introText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    leftBottomImage?: CustomImage;
    rihgtTopImage?: CustomImage;
  } | {
    _key: string;
    _type: "homeTesla";
    brand?: "lucid" | "tesla";
    marginBottom?: boolean;
    imageAlign?: "left" | "right";
    leftImage?: CustomImage;
    bottmRightImage?: CustomImage;
    aboutTesla?: {
      heading?: string;
      subHeading?: string;
      decription?: string;
      topLogo?: CustomImage;
      BottomLogo?: CustomImage;
      button?: CallToAction;
    };
    teslaForm?: TeslaForm;
  } | {
    _key: string;
    _type: "homeWorkFlow";
    image?: CustomImage;
    heading?: string;
    workFlow?: Array<{
      workName?: string;
      workDesc?: string;
      _type: "work";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "imageRichText";
    leftImage?: CustomImage;
    aboutAutocare?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "infoSection";
    heading?: string;
    subheading?: string;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page: string | null;
        post: string | null;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }> | null;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | {
    _key: string;
    _type: "location";
    heading?: string;
    subHeading?: string;
    directionsButtonLabel?: string;
    mobileButton?: string;
    showFilters?: boolean;
    locations: Array<{
      mapId?: string;
      title?: string;
      serviceName?: string;
      poptitle?: string;
      phoneNo?: string;
      address?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          linkType?: "href" | "page" | "post";
          href?: string;
          page?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "page";
          };
          post?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "post";
          };
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      timingLabel1?: string;
      workingHours?: string;
      fridayTiming?: {
        fridayTimingLabel?: string;
        morning?: string;
        evening?: string;
      };
      timingLabel3?: string;
      saturdayTime?: string;
      mapUrl?: string;
      coordinates?: {
        x?: number;
        y?: number;
      };
      relatedServices: Array<{
        _id: string;
        title: string | null;
        slug: Slug | null;
        _type: "service";
      }> | null;
      _key: string;
    }> | null;
  } | {
    _key: string;
    _type: "logoList";
    heading?: string;
    logoList?: Array<{
      logoImage?: CustomImage;
      _type: "logo";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "richTextTitle";
    aboutsection?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "scrollContent";
    title?: Array<string>;
  } | {
    _key: string;
    _type: "serviceBooked";
    titles?: {
      title?: string;
      subTitle?: string;
    };
    heading?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    nextSteps?: {
      steps?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          linkType?: "href" | "page" | "post";
          href?: string;
          page?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "page";
          };
          post?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "post";
          };
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      stepsBackgroundImage?: CustomImage;
    };
    BookingSummary?: {
      title?: string;
      vehicleWorkshop?: string;
      custroInfo?: string;
      branchLabel?: string;
      nameLabel?: string;
      emialLabel?: string;
      contactLabel?: string;
      brandLabel?: string;
      modelLabel?: string;
      plateNoLabel?: string;
      vehicleDetails?: string;
    };
  } | {
    _key: string;
    _type: "serviceBookedTesla";
    heading?: string;
  } | {
    _key: string;
    _type: "serviceCart";
    heading?: string;
    subHeading?: string;
    serviceTitle?: string;
    browseServiceLabel?: string;
    chengeLabel?: string;
    verifySection?: Array<{
      verify?: string;
      countryLabel?: string;
      otpLabel?: string;
      verifyBtnLabel?: string;
      sendOtpButtonLabel?: string;
      sendOtpLabel?: string;
      editBtnLabel?: string;
      _type: "verify";
      _key: string;
    }>;
    appointmentSection?: Array<{
      appointment?: string;
      selectWorkShopLabel?: string;
      workshopPlaceholder?: string;
      availableTimeSlotLabel?: string;
      timeSlotLabel?: string;
      continueBtnLabel?: string;
      editBtnLabel?: string;
      _type: "appointment";
      _key: string;
    }>;
    personalDetailsSection?: Array<{
      appointment?: string;
      fullNameLabel?: string;
      emailLabel?: string;
      verifyYourNameLabel?: string;
      declaration?: string;
      continueBtnLabel?: string;
      editBtnLabel?: string;
      _type: "personalDetails";
      _key: string;
    }>;
    cartSection?: Array<{
      heading?: string;
      scheduleLabel?: string;
      emptyCartHeading?: string;
      emptyCartSubHeading?: string;
      emptyCartImage?: CustomImage;
      submittedBntLable?: string;
      _type: "cart";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "serviceListing";
    heading?: string;
  } | {
    _key: string;
    _type: "termsAndConditionSection";
    title?: string;
    richText?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        linkType?: "href" | "page" | "post";
        href?: string;
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        post?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "teslaForm";
    whiteHeading?: string;
    redHeading?: string;
    teslaImage?: CustomImage;
    teslaLogo?: CustomImage;
    stepOne?: {
      countryLabel?: string;
      phoneLabel?: string;
      phonePlaceholder?: string;
      modelLabel?: string;
      modelPlaceholder?: string;
      yearLabel?: string;
      yearPlaceholder?: string;
      years?: Array<string>;
      plateNumberLabel?: string;
      plateNumberPlaceholder?: string;
      proceed?: string;
    };
    stepTwo?: {
      workshopLabel?: string;
      workshopPlaceholder?: string;
      selectAndProceed?: string;
    };
    stepThree?: {
      fullNameLabel?: string;
      fullNamePlaceholder?: string;
      emailLabel?: string;
      emailPlaceholder?: string;
      declaration?: string;
      scheduleAppointment?: string;
    };
  } | {
    _key: string;
    _type: "testimonial";
    heading?: string;
    subHeading?: string;
  }> | null;
} | null;
// Variable: faqEnQuery
// Query: *[_type == 'faq' ]{  ...,  "question" : question.en,  "answer" : answer.en,}
export type FaqEnQueryResult = Array<{
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string | null;
  answer: BlockContent | null;
}>;
// Variable: faqArQuery
// Query: *[_type == 'faq' ]{  ...,  "question" : question.ar,  "answer" : answer.ar,}
export type FaqArQueryResult = Array<{
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string | null;
  answer: BlockContent | null;
}>;
// Variable: testimonialEnQuery
// Query: *[_type == 'testimonials' ]{  ...,  "review" : review.en,  "name" : name.en,}
export type TestimonialEnQueryResult = Array<{
  _id: string;
  _type: "testimonials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  review: BlockContent | null;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  name: string | null;
  profession?: string;
  stars?: "1" | "2" | "3" | "4" | "5";
}>;
// Variable: testimonialArQuery
// Query: *[_type == 'testimonials' ]{  ...,  "review" : review.ar,  "name" : name.ar,}
export type TestimonialArQueryResult = Array<{
  _id: string;
  _type: "testimonials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  review: BlockContent | null;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  name: string | null;
  profession?: string;
  stars?: "1" | "2" | "3" | "4" | "5";
}>;
// Variable: headerQuery
// Query: *[_type == "fragment" && type == "Header" && language == $language][0] {    ...,    header{    ...,    headerLink {        title,        links[] {          _key,          linkText,          link {            _type,            linkType,            openInNewTab,            href,            path,            "page": page->{            _id,            title,            "slug": slug.current          }          }        }      }},    privacyPolicyLink {        title,        links[] {          _key,          linkText,          link {            _type,            linkType,            openInNewTab,            href,            path,            "page": page->{            _id,            title,            "slug": slug.current          }          }        }      },  }
export type HeaderQueryResult = {
  _id: string;
  _type: "fragment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "Footer" | "Header";
  header: {
    _type: "header";
    callUs?: string;
    contact?: string;
    lang?: LocaleString;
    headerLogo?: CustomImage;
    cornerLogo?: string;
    headerLink: {
      title: string | null;
      links: Array<{
        _key: string;
        linkText: string | null;
        link: {
          _type: "link";
          linkType: "href" | "page" | "post" | null;
          openInNewTab: boolean | null;
          href: string | null;
          path: null;
          page: {
            _id: string;
            title: string | null;
            slug: string | null;
          } | null;
        } | null;
      }> | null;
    } | null;
    privacyPolicyLink?: LinkList;
  } | null;
  footer?: Footer;
  language?: "ar" | "en";
  privacyPolicyLink: null;
} | null;
// Variable: footerQuery
// Query: *[_type == "fragment" && type == "Footer" && language == $language][0] {    footer {    ...,      copyrightText,      linkList {        title,        links[] {          _key,          linkText,          link {            _type,            linkType,            openInNewTab,            href,            path,            "page": page->{            _id,            title,            "slug": slug.current          }          }        }      },      privacyPolicyLink {        title,        links[] {          _key,          linkText,          link {            _type,            linkType,            openInNewTab,            href,            path,            "page": page->{            _id,            title,            "slug": slug.current          }          }        }      },      servicesList {        title,        links[] {          _key,          linkText,          link {            _type,            linkType,            openInNewTab,            href,            path,            "page": page->{              _id,              title,              "slug": slug.current            },          }        }      },    }  }
export type FooterQueryResult = {
  footer: {
    _type: "footer";
    centerFarrari?: CustomImage;
    servicesList: {
      title: string | null;
      links: Array<{
        _key: string;
        linkText: string | null;
        link: {
          _type: "link";
          linkType: "href" | "page" | "post" | null;
          openInNewTab: boolean | null;
          href: string | null;
          path: null;
          page: {
            _id: string;
            title: string | null;
            slug: string | null;
          } | null;
        } | null;
      }> | null;
    } | null;
    linkList: {
      title: string | null;
      links: Array<{
        _key: string;
        linkText: string | null;
        link: {
          _type: "link";
          linkType: "href" | "page" | "post" | null;
          openInNewTab: boolean | null;
          href: string | null;
          path: null;
          page: {
            _id: string;
            title: string | null;
            slug: string | null;
          } | null;
        } | null;
      }> | null;
    } | null;
    agmcLogo?: CustomImage;
    copyrightText: string | null;
    footerLogo2?: CustomImage;
    privacyPolicyLink: {
      title: string | null;
      links: Array<{
        _key: string;
        linkText: string | null;
        link: {
          _type: "link";
          linkType: "href" | "page" | "post" | null;
          openInNewTab: boolean | null;
          href: string | null;
          path: null;
          page: {
            _id: string;
            title: string | null;
            slug: string | null;
          } | null;
        } | null;
      }> | null;
    } | null;
  } | null;
} | null;
// Variable: siteSettingEnQuery
// Query: *[_type == 'settings' ][0]{  ...,  "addThisService" : addThisService.en,  "addVehicleToContinue" : addVehicleToContinue.en,  "serviceAdded" : serviceAdded.en,  "recommended" : recommended.en,  "serviceAlert" : serviceAlert.en,  "bookService" : bookService.en,  "bookServiceDes" : bookServiceDes.en,  "addVehicle" : addVehicle.en,  "testimonialHeading" : testimonialHeading.en,  "testimonialSubHeading" : testimonialSubHeading.en,  "faqTitle" : faqTitle.en,  fragmentItem{  ...,  "addressLine1" : addressLine1.en,  "addressLine2" : addressLine2.en,  "OpenDay" : OpenDay.en,  "endDay" : endDay.en,  "followUs" : followUs.en,  "facebookTitle" : facebookTitle.en,  "instagramTitle" : instagramTitle.en,  "twitterTitle" : twitterTitle.en,  "youtubeTitle" : youtubeTitle.en,},serviceBookForm{...,carImage,stepOne{...,"whiteHeading":whiteHeading.en,"redHeading": redHeading.en,"brandLabel": brandLabel.en,"brandPlaceholder": brandPlaceholder.en,"modelLabel": modelLabel.en,"modelPlaceholder": modelPlaceholder.en,"yearLabel": yearLabel.en,"yearPlaceholder": yearPlaceholder.en,"numberPlateLabel": numberPlateLabel.en,"numberPlatePlaceholder": numberPlatePlaceholder.en,"proceedBtn": proceedBtn.en},stepTwo{...,"whiteHeading":whiteHeading.en,"redHeading": redHeading.en,"nameLabel": nameLabel.en,"namePlaceholder": namePlaceholder.en,"countryLabel": countryLabel.en,"phoneLabel": phoneLabel.en,"phonePlaceholder": phonePlaceholder.en,"emailLabel": emailLabel.en,"emailPlaceholder": emailPlaceholder.en,"proceedBtn": proceedBtn.en}}}
export type SiteSettingEnQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
  fragmentItem: {
    pitstopContact?: string;
    pitstopEmail?: string;
    addressLine1: string | null;
    addressLine2: string | null;
    openTime?: string;
    closeTime?: string;
    OpenDay: string | null;
    endDay: string | null;
    followUs: string | null;
    facebookTitle: string | null;
    facebookLink?: string;
    instagramTitle: string | null;
    instagramLink?: string;
    twitterTitle: string | null;
    twitterLink?: string;
    youtubeTitle: string | null;
    youtubeLink?: string;
  } | null;
  addThisService: string | null;
  addVehicleToContinue: string | null;
  serviceAdded: string | null;
  recommended: string | null;
  serviceAlert: string | null;
  bookService: string | null;
  bookServiceDes: string | null;
  addVehicle: string | null;
  testimonialHeading: string | null;
  testimonialSubHeading: string | null;
  faqTitle: string | null;
  serviceBookForm: {
    carImage: CustomImage | null;
    stepOne: {
      whiteHeading: string | null;
      redHeading: string | null;
      brandLabel: string | null;
      brandPlaceholder: string | null;
      modelLabel: string | null;
      modelPlaceholder: string | null;
      yearLabel: string | null;
      yearPlaceholder: string | null;
      numberPlateLabel: string | null;
      numberPlatePlaceholder: string | null;
      proceedBtn: string | null;
    } | null;
    stepTwo: {
      whiteHeading: string | null;
      redHeading: string | null;
      nameLabel: string | null;
      namePlaceholder: string | null;
      countryLabel: string | null;
      phoneLabel: string | null;
      phonePlaceholder: string | null;
      emailLabel: string | null;
      emailPlaceholder: string | null;
      proceedBtn: string | null;
    } | null;
  } | null;
  brands?: Array<{
    carImage?: CustomImage;
    brandTitle?: string;
    brandValue?: string;
    _type: "brand";
    _key: string;
  }>;
} | null;
// Variable: siteSettingArQuery
// Query: *[_type == 'settings' ][0]{  ...,  "addThisService" : addThisService.ar,  "addVehicleToContinue" : addVehicleToContinue.ar,  "serviceAdded" : serviceAdded.ar,  "recommended" : recommended.ar,  "serviceAlert" : serviceAlert.ar,  "bookService" : bookService.ar,  "bookServiceDes" : bookServiceDes.ar,  "addVehicle" : addVehicle.ar,  "testimonialHeading" : testimonialHeading.ar,  "testimonialSubHeading" : testimonialSubHeading.ar,  "faqTitle" : faqTitle.ar,  fragmentItem{  ...,  "addressLine1" : addressLine1.ar,  "addressLine2" : addressLine2.ar,  "OpenDay" : OpenDay.ar,  "endDay" : endDay.ar,  "followUs" : followUs.ar,  "facebookTitle" : facebookTitle.ar,  "instagramTitle" : instagramTitle.ar,  "twitterTitle" : twitterTitle.ar,  "youtubeTitle" : youtubeTitle.ar,},serviceBookForm{...,carImage,stepOne{...,"whiteHeading":whiteHeading.ar,"redHeading": redHeading.ar,"brandLabel": brandLabel.ar,"brandPlaceholder": brandPlaceholder.ar,"modelLabel": modelLabel.ar,"modelPlaceholder": modelPlaceholder.ar,"yearLabel": yearLabel.ar,"yearPlaceholder": yearPlaceholder.ar,"numberPlateLabel": numberPlateLabel.ar,"numberPlatePlaceholder": numberPlatePlaceholder.ar,"proceedBtn": proceedBtn.ar},stepTwo{...,"whiteHeading":whiteHeading.ar,"redHeading": redHeading.ar,"nameLabel": nameLabel.ar,"namePlaceholder": namePlaceholder.ar,"countryLabel": countryLabel.ar,"phoneLabel": phoneLabel.ar,"phonePlaceholder": phonePlaceholder.ar,"emailLabel": emailLabel.ar,"emailPlaceholder": emailPlaceholder.ar,"proceedBtn": proceedBtn.ar}}}
export type SiteSettingArQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
  fragmentItem: {
    pitstopContact?: string;
    pitstopEmail?: string;
    addressLine1: string | null;
    addressLine2: string | null;
    openTime?: string;
    closeTime?: string;
    OpenDay: string | null;
    endDay: string | null;
    followUs: string | null;
    facebookTitle: string | null;
    facebookLink?: string;
    instagramTitle: string | null;
    instagramLink?: string;
    twitterTitle: string | null;
    twitterLink?: string;
    youtubeTitle: string | null;
    youtubeLink?: string;
  } | null;
  addThisService: string | null;
  addVehicleToContinue: string | null;
  serviceAdded: string | null;
  recommended: string | null;
  serviceAlert: string | null;
  bookService: string | null;
  bookServiceDes: string | null;
  addVehicle: string | null;
  testimonialHeading: string | null;
  testimonialSubHeading: string | null;
  faqTitle: string | null;
  serviceBookForm: {
    carImage: CustomImage | null;
    stepOne: {
      whiteHeading: string | null;
      redHeading: string | null;
      brandLabel: string | null;
      brandPlaceholder: string | null;
      modelLabel: string | null;
      modelPlaceholder: string | null;
      yearLabel: string | null;
      yearPlaceholder: string | null;
      numberPlateLabel: string | null;
      numberPlatePlaceholder: string | null;
      proceedBtn: string | null;
    } | null;
    stepTwo: {
      whiteHeading: string | null;
      redHeading: string | null;
      nameLabel: string | null;
      namePlaceholder: string | null;
      countryLabel: string | null;
      phoneLabel: string | null;
      phonePlaceholder: string | null;
      emailLabel: string | null;
      emailPlaceholder: string | null;
      proceedBtn: string | null;
    } | null;
  } | null;
  brands?: Array<{
    carImage?: CustomImage;
    brandTitle?: string;
    brandValue?: string;
    _type: "brand";
    _key: string;
  }>;
} | null;
// Variable: getServiceDetailQuery
// Query: *[_type == 'service' && slug.current == $slug][0]{     ...,     link -> {              "slug": slug.current          }  }
export type GetServiceDetailQueryResult = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  serviceIcon?: CustomImage;
  thumbnail?: CustomImage;
  shceduleNow?: string;
  pageBuilder?: Array<{
    _key: string;
  } & ServiceCard>;
  noVehicleImage?: CustomImage;
  noVehicleHeading?: string;
  noVehicleText?: string;
  addVehicleLabel?: string;
  emptyCartCarImage?: CustomImage;
  heading?: string;
  subHeading?: string;
  browseServiceCtaLabel?: string;
  changeCtaLabel?: string;
  cartLabel?: string;
  estimatedTotalLabel?: string;
  taxLabel?: string;
  submitCtaLabel?: string;
  seo?: SeoMetaFields;
  language?: "ar" | "en";
  link: null;
} | null;
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<{
  slug: string | null;
  _type: "page";
  _updatedAt: string;
} | {
  slug: string | null;
  _type: "post";
  _updatedAt: string;
}>;
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page: string | null;
      post: string | null;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    firstName: string | null;
    lastName: string | null;
    picture: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
} | null;
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string | null;
}>;
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string | null;
}>;
// Variable: serviceEnQuery
// Query: *[_type == 'service' && language == "en"]{  ...,}
export type ServiceEnQueryResult = Array<{
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  serviceIcon?: CustomImage;
  thumbnail?: CustomImage;
  shceduleNow?: string;
  pageBuilder?: Array<{
    _key: string;
  } & ServiceCard>;
  noVehicleImage?: CustomImage;
  noVehicleHeading?: string;
  noVehicleText?: string;
  addVehicleLabel?: string;
  emptyCartCarImage?: CustomImage;
  heading?: string;
  subHeading?: string;
  browseServiceCtaLabel?: string;
  changeCtaLabel?: string;
  cartLabel?: string;
  estimatedTotalLabel?: string;
  taxLabel?: string;
  submitCtaLabel?: string;
  seo?: SeoMetaFields;
  language?: "ar" | "en";
}>;
// Variable: serviceArQuery
// Query: *[_type == 'service' && language == "ar"]{  ...,}
export type ServiceArQueryResult = Array<{
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  serviceIcon?: CustomImage;
  thumbnail?: CustomImage;
  shceduleNow?: string;
  pageBuilder?: Array<{
    _key: string;
  } & ServiceCard>;
  noVehicleImage?: CustomImage;
  noVehicleHeading?: string;
  noVehicleText?: string;
  addVehicleLabel?: string;
  emptyCartCarImage?: CustomImage;
  heading?: string;
  subHeading?: string;
  browseServiceCtaLabel?: string;
  changeCtaLabel?: string;
  cartLabel?: string;
  estimatedTotalLabel?: string;
  taxLabel?: string;
  submitCtaLabel?: string;
  seo?: SeoMetaFields;
  language?: "ar" | "en";
}>;
// Variable: offerDetailsQuery
// Query: *[_type == 'offer' && slug.current == $slug][0]{     ...,  }
export type OfferDetailsQueryResult = {
  _id: string;
  _type: "offer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  thumbnail?: CustomImage;
  buttonText?: string;
  detailImage?: CustomImage;
  richText?: Array<{
    offerRichText?: BlockContent;
    _type: "richText";
    _key: string;
  }>;
  language?: "ar" | "en";
} | null;
// Variable: blogDetailsQuery
// Query: *[_type == 'blog' && slug.current == $slug][0]{     ...,  }
export type BlogDetailsQueryResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  IsHomePage?: boolean;
  categoryTags?: Tags;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  blogDate?: string;
  thumbnailImage?: CustomImage;
  blogImage?: CustomImage;
  pageBuilder?: Array<{
    _key: string;
  } & BlogImage | {
    _key: string;
  } & RichText>;
  language?: "ar" | "en";
} | null;
// Variable: FeaturedBlogEnQuery
// Query: *[_type == 'blog' && IsHomePage == true && language == "en"]{  ...,}
export type FeaturedBlogEnQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  IsHomePage?: boolean;
  categoryTags?: Tags;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  blogDate?: string;
  thumbnailImage?: CustomImage;
  blogImage?: CustomImage;
  pageBuilder?: Array<{
    _key: string;
  } & BlogImage | {
    _key: string;
  } & RichText>;
  language?: "ar" | "en";
}>;
// Variable: FeaturedBlogArQuery
// Query: *[_type == 'blog' && IsHomePage == true && language == "ar"]{  ...,}
export type FeaturedBlogArQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  IsHomePage?: boolean;
  categoryTags?: Tags;
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  blogDate?: string;
  thumbnailImage?: CustomImage;
  blogImage?: CustomImage;
  pageBuilder?: Array<{
    _key: string;
  } & BlogImage | {
    _key: string;
  } & RichText>;
  language?: "ar" | "en";
}>;
// Variable: getRelatedBlogsQuery
// Query: *[_type == "blog" &&     _id != $currentBlogId &&     language == $locale &&    defined(categoryTags) &&    (      count((categoryTags[]._key)[@ in $tagIds]) > 0 ||      count((categoryTags[]._ref)[@ in $tagIds]) > 0 ||      count((categoryTags[].value)[@ in $tagIds]) > 0    )  ] | order(_createdAt desc) [0...3] {    _id,    title,    slug,    blogDate,    thumbnailImage,    categoryTags[] {      _key,      label,      value    }  }
export type GetRelatedBlogsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  blogDate: string | null;
  thumbnailImage: CustomImage | null;
  categoryTags: Array<{
    _key: string;
    label: string | null;
    value: string | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"settings\"][0]": SettingsQueryResult;
    "\n  *[_type == 'page' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    \"pageBuilder\": pageBuilder[]{\n      ...,\n      _type == \"callToAction\" => {\n        \n  link {\n      ...,\n      \n  _type == \"link\" => {\n    \"page\": page->slug.current,\n    \"post\": post->slug.current\n  }\n\n      }\n,\n      },\n      _type == \"location\" => {\n      ...,\n      locations[]{\n         ...,\n        \"relatedServices\": relatedServices[]->{\n            _id,\n            title,\n            slug,\n            _type\n          }\n      }\n      \n},\n      _type == \"infoSection\" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == \"link\" => {\n    \"page\": page->slug.current,\n    \"post\": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n": GetPageQueryResult;
    "*[_type == 'faq' ]{\n  ...,\n  \"question\" : question.en,\n  \"answer\" : answer.en,\n}": FaqEnQueryResult;
    "*[_type == 'faq' ]{\n  ...,\n  \"question\" : question.ar,\n  \"answer\" : answer.ar,\n}": FaqArQueryResult;
    "*[_type == 'testimonials' ]{\n  ...,\n  \"review\" : review.en,\n  \"name\" : name.en,\n}": TestimonialEnQueryResult;
    "*[_type == 'testimonials' ]{\n  ...,\n  \"review\" : review.ar,\n  \"name\" : name.ar,\n}": TestimonialArQueryResult;
    "\n  *[_type == \"fragment\" && type == \"Header\" && language == $language][0] {\n    ...,\n    header{\n    ...,\n    headerLink {\n        title,\n        links[] {\n          _key,\n          linkText,\n          link {\n            _type,\n            linkType,\n            openInNewTab,\n            href,\n            path,\n            \"page\": page->{\n            _id,\n            title,\n            \"slug\": slug.current\n          }\n          }\n        }\n      }\n},\n    privacyPolicyLink {\n        title,\n        links[] {\n          _key,\n          linkText,\n          link {\n            _type,\n            linkType,\n            openInNewTab,\n            href,\n            path,\n            \"page\": page->{\n            _id,\n            title,\n            \"slug\": slug.current\n          }\n          }\n        }\n      },\n  }\n  ": HeaderQueryResult;
    "\n  *[_type == \"fragment\" && type == \"Footer\" && language == $language][0] {\n    footer {\n    ...,\n      copyrightText,\n      linkList {\n        title,\n        links[] {\n          _key,\n          linkText,\n          link {\n            _type,\n            linkType,\n            openInNewTab,\n            href,\n            path,\n            \"page\": page->{\n            _id,\n            title,\n            \"slug\": slug.current\n          }\n          }\n        }\n      },\n      privacyPolicyLink {\n        title,\n        links[] {\n          _key,\n          linkText,\n          link {\n            _type,\n            linkType,\n            openInNewTab,\n            href,\n            path,\n            \"page\": page->{\n            _id,\n            title,\n            \"slug\": slug.current\n          }\n          }\n        }\n      },\n      servicesList {\n        title,\n        links[] {\n          _key,\n          linkText,\n          link {\n            _type,\n            linkType,\n            openInNewTab,\n            href,\n            path,\n            \"page\": page->{\n              _id,\n              title,\n              \"slug\": slug.current\n            },\n          }\n        }\n      },\n    }\n  }\n": FooterQueryResult;
    "*[_type == 'settings' ][0]{\n  ...,\n  \"addThisService\" : addThisService.en,\n  \"addVehicleToContinue\" : addVehicleToContinue.en,\n  \"serviceAdded\" : serviceAdded.en,\n  \"recommended\" : recommended.en,\n  \"serviceAlert\" : serviceAlert.en,\n  \"bookService\" : bookService.en,\n  \"bookServiceDes\" : bookServiceDes.en,\n  \"addVehicle\" : addVehicle.en,\n  \"testimonialHeading\" : testimonialHeading.en,\n  \"testimonialSubHeading\" : testimonialSubHeading.en,\n  \"faqTitle\" : faqTitle.en,\n  fragmentItem{\n  ...,\n  \"addressLine1\" : addressLine1.en,\n  \"addressLine2\" : addressLine2.en,\n  \"OpenDay\" : OpenDay.en,\n  \"endDay\" : endDay.en,\n  \"followUs\" : followUs.en,\n  \"facebookTitle\" : facebookTitle.en,\n  \"instagramTitle\" : instagramTitle.en,\n  \"twitterTitle\" : twitterTitle.en,\n  \"youtubeTitle\" : youtubeTitle.en,\n},\nserviceBookForm{\n...,\ncarImage,\nstepOne{\n...,\n\"whiteHeading\":whiteHeading.en,\n\"redHeading\": redHeading.en,\n\"brandLabel\": brandLabel.en,\n\"brandPlaceholder\": brandPlaceholder.en,\n\"modelLabel\": modelLabel.en,\n\"modelPlaceholder\": modelPlaceholder.en,\n\"yearLabel\": yearLabel.en,\n\"yearPlaceholder\": yearPlaceholder.en,\n\"numberPlateLabel\": numberPlateLabel.en,\n\"numberPlatePlaceholder\": numberPlatePlaceholder.en,\n\"proceedBtn\": proceedBtn.en\n},\nstepTwo{\n...,\n\"whiteHeading\":whiteHeading.en,\n\"redHeading\": redHeading.en,\n\"nameLabel\": nameLabel.en,\n\"namePlaceholder\": namePlaceholder.en,\n\"countryLabel\": countryLabel.en,\n\"phoneLabel\": phoneLabel.en,\n\"phonePlaceholder\": phonePlaceholder.en,\n\"emailLabel\": emailLabel.en,\n\"emailPlaceholder\": emailPlaceholder.en,\n\"proceedBtn\": proceedBtn.en\n}\n}\n}": SiteSettingEnQueryResult;
    "*[_type == 'settings' ][0]{\n  ...,\n  \"addThisService\" : addThisService.ar,\n  \"addVehicleToContinue\" : addVehicleToContinue.ar,\n  \"serviceAdded\" : serviceAdded.ar,\n  \"recommended\" : recommended.ar,\n  \"serviceAlert\" : serviceAlert.ar,\n  \"bookService\" : bookService.ar,\n  \"bookServiceDes\" : bookServiceDes.ar,\n  \"addVehicle\" : addVehicle.ar,\n  \"testimonialHeading\" : testimonialHeading.ar,\n  \"testimonialSubHeading\" : testimonialSubHeading.ar,\n  \"faqTitle\" : faqTitle.ar,\n  fragmentItem{\n  ...,\n  \"addressLine1\" : addressLine1.ar,\n  \"addressLine2\" : addressLine2.ar,\n  \"OpenDay\" : OpenDay.ar,\n  \"endDay\" : endDay.ar,\n  \"followUs\" : followUs.ar,\n  \"facebookTitle\" : facebookTitle.ar,\n  \"instagramTitle\" : instagramTitle.ar,\n  \"twitterTitle\" : twitterTitle.ar,\n  \"youtubeTitle\" : youtubeTitle.ar,\n},\nserviceBookForm{\n...,\ncarImage,\nstepOne{\n...,\n\"whiteHeading\":whiteHeading.ar,\n\"redHeading\": redHeading.ar,\n\"brandLabel\": brandLabel.ar,\n\"brandPlaceholder\": brandPlaceholder.ar,\n\"modelLabel\": modelLabel.ar,\n\"modelPlaceholder\": modelPlaceholder.ar,\n\"yearLabel\": yearLabel.ar,\n\"yearPlaceholder\": yearPlaceholder.ar,\n\"numberPlateLabel\": numberPlateLabel.ar,\n\"numberPlatePlaceholder\": numberPlatePlaceholder.ar,\n\"proceedBtn\": proceedBtn.ar\n},\nstepTwo{\n...,\n\"whiteHeading\":whiteHeading.ar,\n\"redHeading\": redHeading.ar,\n\"nameLabel\": nameLabel.ar,\n\"namePlaceholder\": namePlaceholder.ar,\n\"countryLabel\": countryLabel.ar,\n\"phoneLabel\": phoneLabel.ar,\n\"phonePlaceholder\": phonePlaceholder.ar,\n\"emailLabel\": emailLabel.ar,\n\"emailPlaceholder\": emailPlaceholder.ar,\n\"proceedBtn\": proceedBtn.ar\n}\n}\n}": SiteSettingArQueryResult;
    "\n  *[_type == 'service' && slug.current == $slug][0]{\n     ...,\n     link -> {\n              \"slug\": slug.current\n          }\n  }\n": GetServiceDetailQueryResult;
    "\n  *[_type == \"page\" || _type == \"post\" && defined(slug.current)] | order(_type asc) {\n    \"slug\": slug.current,\n    _type,\n    _updatedAt,\n  }\n": SitemapDataResult;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{firstName, lastName, picture},\n\n  }\n": AllPostsQueryResult;
    "\n  *[_type == \"post\" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{firstName, lastName, picture},\n\n  }\n": MorePostsQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == \"link\" => {\n    \"page\": page->slug.current,\n    \"post\": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  \"status\": select(_originalId in path(\"drafts.**\") => \"draft\", \"published\"),\n  \"title\": coalesce(title, \"Untitled\"),\n  \"slug\": slug.current,\n  excerpt,\n  coverImage,\n  \"date\": coalesce(date, _updatedAt),\n  \"author\": author->{firstName, lastName, picture},\n\n  }\n": PostQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current)]\n  {\"slug\": slug.current}\n": PostPagesSlugsResult;
    "\n  *[_type == \"page\" && defined(slug.current)]\n  {\"slug\": slug.current}\n": PagesSlugsResult;
    "*[_type == 'service' && language == \"en\"]{\n  ...,\n}": ServiceEnQueryResult;
    "*[_type == 'service' && language == \"ar\"]{\n  ...,\n}": ServiceArQueryResult;
    "\n  *[_type == 'offer' && slug.current == $slug][0]{\n     ...,\n  }\n": OfferDetailsQueryResult;
    "\n  *[_type == 'blog' && slug.current == $slug][0]{\n     ...,\n  }\n": BlogDetailsQueryResult;
    "*[_type == 'blog' && IsHomePage == true && language == \"en\"]{\n  ...,\n}": FeaturedBlogEnQueryResult;
    "*[_type == 'blog' && IsHomePage == true && language == \"ar\"]{\n  ...,\n}": FeaturedBlogArQueryResult;
    "\n  *[_type == \"blog\" && \n    _id != $currentBlogId && \n    language == $locale &&\n    defined(categoryTags) &&\n    (\n      count((categoryTags[]._key)[@ in $tagIds]) > 0 ||\n      count((categoryTags[]._ref)[@ in $tagIds]) > 0 ||\n      count((categoryTags[].value)[@ in $tagIds]) > 0\n    )\n  ] | order(_createdAt desc) [0...3] {\n    _id,\n    title,\n    slug,\n    blogDate,\n    thumbnailImage,\n    categoryTags[] {\n      _key,\n      label,\n      value\n    }\n  }\n": GetRelatedBlogsQueryResult;
  }
}
